### ISSUE TITLE
Please add release notes for version 2.1 through 2.3.

### ISSUE THREAD

**Issue by nzall** [hazendaz/displaytag#106]
The release notes are currently only updated up to version 2.0. there don't appear to be any release notes, change logs or anything similar for versions 2.1 through 2.3. And while you do mention in #7 that versions after 2.0 are just bugfixes, I'd still like to know what these bugfixes are so I know if there are any bugs that I had to use a workaround for in the older version that are no longer needed in the modern version.

**Comment by hazendaz** [comment]
Only library updates and vulnerability fixes.  This is maintenance only.  No new features no changes to apis.  Github shows the commits between releases.  Please check there as release notes wont say much at all.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by hazendaz** [comment]
closing issue.  Added some release notes but as noted, look at changelog itself.  No clue over the last 5 years really what all bug fixes were applied.  This repo only exists due to lack of time personally for me to update a larger project that uses it.   Its really a dead project thus only bug fixes, library updates, code cleanup.  It should be compatible with any old versions.  The original author had changes for probably a year after 1.2 was released that were also included here.  When this was pulled from the prior repo it was exacted out via tooling so it came directly from the original at that time (~2016).
