### ISSUE TITLE
TableModel has a paginated list in rowListFull

### ISSUE THREAD

**Issue by gorbeia** [hazendaz/displaytag#3]
Hello,

The TableModel object is filled in TableTag. Only the paginated list is filled in rowListFull. This attribute should contain the full list of records while the paginated list should be in rowListPage.

This prevents the export feature to work as it only exports the paginated list instead of the full list.

Regards.

**Comment by gorbeia** [comment]
It seems that in TableTag#initParameters when we are rendering a partialList the tableIterator is set only to the paginated sublist. It doesn't make sense to restrict it in the iterator because we need later to fill both rowListPate and rowListFull.

Setting the iterator with the full list does not break any current test.

**Comment by hazendaz** [comment]
Can you provide a pull request?

Get Outlook for Android<https://aka.ms/ghei36>



On Thu, Dec 1, 2016 at 2:10 AM -0500, "Iñaki Ibarrola Atxa" <notifications@github.com<mailto:notifications@github.com>> wrote:


It seems that in TableTag#initParameters when we are rendering a partialList the tableIterator is set only to the paginated sublist. It doesn't make sense to restrict it in the iterator because we need later to fill both rowListPate and rowListFull.

Setting the iterator with the full list does not break any current test.

-

**Comment by gorbeia** [comment]
I am working on it. I also expect to provide some tests.

**Comment by hazendaz** [comment]
Great!  Thanks.

Get Outlook for Android<https://aka.ms/ghei36>



On Fri, Dec 2, 2016 at 3:49 AM -0500, "Iñaki Ibarrola Atxa" <notifications@github.com<mailto:notifications@github.com>> wrote:


I am working on it. I also expect to provide some tests.

-

**Comment by hazendaz** [comment]
Closed via #5
